### ISSUE TITLE
FR: Convert to mkv 

### ISSUE THREAD

**Issue by karan** [gacopl/dvmkv2mp4#23]
This looks like a great script that I can't wait to try. One thing I like though is keeping all my content in mkv containers (which are all self contained). It would be nice to have all the features of this script (audio conversion, subs etc) but remux the output to mkv instead of mp4.

**Comment by gacopl** [comment]
The reason for this script was because many devices don't support DV in
MKVs properly only in MP4 since the source is assumed to be mkv no sens to
convert it to mkv again. All the audio and subs conversion is only to make
it work in MP4 container. Otherwise i wouldn't touch it.

Bottom line is if you can do PR i can consider accepting it but i don't see
a point spending time on it.

If you like the guts of it feel free to fork it and do mkv equivalent
though i really don't see a point :)

śr., 8 lut 2023 o 16:31 Karan Goel ***@***.***> napisał(a):

**Comment by gacopl** [comment]
Because my tv plays better mp4 than shield does mkv in p8, shield has red
push in all dv profiles except profile 5 at least that's what i saw, so i
decided to use emby on my tv and have all DV files converted to mp4 P5 or
P8 as tv does only mp4 dvs mkv dvs dont work at all. Shield plays them all
even slightly broken files but i can see color differences and i did not
calibrate my TV to then bear with Shield color discrepancies.

And i assure you there is difference otherwise i wouldnt spend time on
making this script doing all the research if shield could pull it off

śr., 8 lut 2023 o 18:03 Karan Goel ***@***.***> napisał(a):
